In [1]:
import torch

In [2]:
x = torch.tensor(3.0,requires_grad=True)

In [3]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [4]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [5]:
z.backward()

In [10]:
x.grad

tensor(-5.4668)

In [6]:
a = torch.tensor([1.0,2.0,3.0,4.0,5.0],requires_grad=True)
a

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [7]:
b = torch.mean(a**2)
b

tensor(11., grad_fn=<MeanBackward0>)

In [8]:
b.backward()

In [9]:
print(a.grad)

tensor([0.4000, 0.8000, 1.2000, 1.6000, 2.0000])


In [11]:
p = x.detach()
p

tensor(3.)

In [12]:
a

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [15]:
with torch.no_grad():
  q = torch.mean(a**2)

In [16]:
q

tensor(11.)