###Import all libraries

In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'],inplace = True)

In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
x = df.drop(columns=['diagnosis'])
y = df['diagnosis']

###Spiltting the dataset into training set and testing set

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=54,test_size=0.25)

###Scaling the data

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [9]:
x_train

array([[-0.6230448 , -0.44882899, -0.63935713, ..., -0.39548242,
        -1.14826509, -1.3244196 ],
       [-0.37188685, -0.10414617, -0.40151172, ..., -0.49446774,
        -0.27728046, -0.66112116],
       [ 0.26611209,  0.11011612,  0.17024013, ..., -0.89384383,
        -0.44017453, -1.29579593],
       ...,
       [ 2.05308651,  0.87400777,  1.9194736 , ...,  1.34441094,
        -0.14763007, -0.50259009],
       [-0.39786871, -0.46280261, -0.4275195 , ..., -0.91757533,
        -0.37036278, -0.85378046],
       [-0.4094162 ,  0.34300992, -0.38976626, ..., -0.06698855,
        -1.13829199,  0.02584684]])

In [10]:
y_train

275    B
362    B
165    B
1      M
429    B
      ..
312    B
320    B
23     M
325    B
111    B
Name: diagnosis, Length: 426, dtype: object

###Performing Label Encodeing to convert the datatype into integer

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,

In [13]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0])

###Converting array to tensor

In [14]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
x_train_tensor

tensor([[-0.6230, -0.4488, -0.6394,  ..., -0.3955, -1.1483, -1.3244],
        [-0.3719, -0.1041, -0.4015,  ..., -0.4945, -0.2773, -0.6611],
        [ 0.2661,  0.1101,  0.1702,  ..., -0.8938, -0.4402, -1.2958],
        ...,
        [ 2.0531,  0.8740,  1.9195,  ...,  1.3444, -0.1476, -0.5026],
        [-0.3979, -0.4628, -0.4275,  ..., -0.9176, -0.3704, -0.8538],
        [-0.4094,  0.3430, -0.3898,  ..., -0.0670, -1.1383,  0.0258]],
       dtype=torch.float64)

In [16]:
x_train_tensor.shape

torch.Size([426, 30])

In [18]:
y_train_tensor.shape

torch.Size([426])

###Defining the model

In [26]:
class MySimpleNN():
  def __init__(self,x):
    self.weights = torch.rand(x.shape[1],1,dtype = torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad = True)

  def forward(self,x):
    z = torch.matmul(x,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    loss = torch.mean((y_pred - y)**2)
    return loss



In [27]:
learning_rate = 0.01
epochs = 50

###Training Pipeline

In [28]:
#Create Model
model = MySimpleNN(x_train_tensor)

#Define Loop
for epoch in range(epochs):

  #Forward Pass
  y_pred = model.forward(x_train_tensor)

  #Calculate Loss
  loss = model.loss_function(y_pred,y_train_tensor)

  #Backward Pass
  loss.backward()

  #Update Parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #Printing Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')



Epoch: 1, Loss: 0.44745322464950893
Epoch: 2, Loss: 0.44745142946158545
Epoch: 3, Loss: 0.4474496341910324
Epoch: 4, Loss: 0.4474478388379956
Epoch: 5, Loss: 0.4474460434026207
Epoch: 6, Loss: 0.44744424788505355
Epoch: 7, Loss: 0.44744245228543933
Epoch: 8, Loss: 0.4474406566039237
Epoch: 9, Loss: 0.44743886084065165
Epoch: 10, Loss: 0.44743706499576835
Epoch: 11, Loss: 0.4474352690694185
Epoch: 12, Loss: 0.4474334730617471
Epoch: 13, Loss: 0.44743167697289843
Epoch: 14, Loss: 0.44742988080301727
Epoch: 15, Loss: 0.4474280845522478
Epoch: 16, Loss: 0.44742628822073416
Epoch: 17, Loss: 0.4474244918086203
Epoch: 18, Loss: 0.4474226953160503
Epoch: 19, Loss: 0.4474208987431676
Epoch: 20, Loss: 0.4474191020901159
Epoch: 21, Loss: 0.4474173053570386
Epoch: 22, Loss: 0.44741550854407897
Epoch: 23, Loss: 0.44741371165138005
Epoch: 24, Loss: 0.44741191467908475
Epoch: 25, Loss: 0.44741011762733607
Epoch: 26, Loss: 0.4474083204962763
Epoch: 27, Loss: 0.44740652328604824
Epoch: 28, Loss: 0.4474

In [29]:
model.bias

tensor([-0.0018], dtype=torch.float64, requires_grad=True)

###Model Evalulation

In [32]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5467259883880615
