###The torch.nn module in PyTorch is a core library that provides a wide array of classes & functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre built layers, loss functions, activation functions, etc; enabling you to focus on designing and exprementing with model architecture.

In [17]:
 #Import libraries and Define model class for Single Neural Network
import torch
import torch.nn as nn

### Importing Libraries and Defining the Model Class

This cell imports necessary libraries and defines the architecture of a single-layer neural network using PyTorch's `nn.Module`.

**Concepts:**

* **torch.nn:** PyTorch's neural network module containing building blocks for creating neural networks.
* **nn.Module:** Base class for all neural network modules in PyTorch.
* **nn.Linear:** Applies a linear transformation to the incoming data.
* **nn.Sigmoid:** Applies the sigmoid activation function.
* **__init__:** Constructor of the class, where layers and components are initialized.
* **forward:** Defines the forward pass of the model, specifying how data flows through the network.

In [18]:
class Model(nn.Module):
  def __init__(self,no_features):
    super().__init__()
    self.linear = nn.Linear(no_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

### Creating a Fake Dataset and Model Instance

This cell creates a fake dataset using `torch.rand` and instantiates the `Model` class defined earlier.

**Concepts:**

* **torch.rand:** Generates a tensor with random numbers drawn from a uniform distribution.
* **Model(features.shape[1]):** Creates an instance of the `Model` class, passing the number of input features.
* **model(features):** Calls the `forward` method of the model to perform a forward pass.

In [19]:
#Creating a fake dataset
features = torch.rand(20,5)

#Creating instance of the model
model = Model(features.shape[1])

#Calling the model for forward pass
#model.forward(features)
model(features)

tensor([[0.4574],
        [0.4296],
        [0.4859],
        [0.4202],
        [0.3494],
        [0.3462],
        [0.3848],
        [0.4676],
        [0.4338],
        [0.4036],
        [0.3621],
        [0.4599],
        [0.4448],
        [0.4890],
        [0.4537],
        [0.4257],
        [0.4453],
        [0.4309],
        [0.3635],
        [0.3833]], grad_fn=<SigmoidBackward0>)

### Accessing Model Weights

This cell shows how to access the weights of the linear layer in the model.

**Concepts:**

* **model.linear.weight:** Accesses the weight tensor of the linear layer.

In [20]:
#Showing model weights
model.linear.weight

Parameter containing:
tensor([[-0.4464, -0.4231,  0.3632,  0.1764,  0.2544]], requires_grad=True)

### Accessing Model Bias

This cell shows how to access the bias of the linear layer in the model.

**Concepts:**

* **model.linear.bias:** Accesses the bias tensor of the linear layer.

In [21]:
#Showing model bias
model.linear.bias

Parameter containing:
tensor([-0.2947], requires_grad=True)

In [22]:
!pip install torchinfo

### Model Summary using torchinfo

This cell uses the `summary` function from the `torchinfo` library to print a summary of the model architecture. The input size is specified as (1, 5), which indicates the dimensions of the input to the model.

**Concepts:**

* `from torchinfo import summary`: Imports the `summary` function from the `torchinfo` library.
* `summary(model, input_size=(1, 5))`:  Calls the summary function, providing the model and the size of the input tensor as arguments.


* **torchinfo:**  A library to provide information about PyTorch models, such as the number of parameters, the size of the input and output tensors, and the computational cost.

**Note:** Make sure to install `torchinfo` library before trying to summarize the model in subsequent cells.

In [23]:
from torchinfo import summary

summary(model,input_size=(1,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1, 1]                    --
├─Linear: 1-1                            [1, 1]                    6
├─Sigmoid: 1-2                           [1, 1]                    --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Creating a Multilayer Neural Network Model

This cell defines a more complex neural network with multiple layers using PyTorch's `nn.Module`. This model introduces a hidden layer with a ReLU activation function, demonstrating a typical structure for multilayer perceptrons (MLPs).

**Concepts:**

* **Multilayer Perceptron (MLP):** A type of feedforward neural network consisting of multiple layers of interconnected nodes (neurons).
* **Hidden Layer:** A layer between the input and output layers that processes the input data and extracts features.
* **nn.ReLU:** Applies the Rectified Linear Unit (ReLU) activation function, introducing non-linearity to the model.
* **Multiple Linear Layers:** The model uses two linear layers (`nn.Linear`) for transforming the data at different stages.

In [28]:
class Model1(nn.Module):
  def __init__(self,no_features):
    super().__init__()
    self.linear1 = nn.Linear(no_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

### Instantiating and Using the Multilayer Model

This cell creates a fake dataset and an instance of the `Model1` class (the multilayer model defined in the previous cell). It then performs a forward pass using the fake data.

**Concepts:**

* **Model Instantiation:** Creates an instance of the `Model1` class, passing the number of input features.
* **Forward Pass:** Calls the `forward` method of the model to process the input data and obtain the output.

In [29]:
features = torch.rand(15,5)
model1 = Model1(features.shape[1])
model1(features)

tensor([[0.4762],
        [0.5015],
        [0.4655],
        [0.5249],
        [0.4854],
        [0.5118],
        [0.4889],
        [0.5081],
        [0.5352],
        [0.4552],
        [0.4948],
        [0.4931],
        [0.4986],
        [0.4831],
        [0.5338]], grad_fn=<SigmoidBackward0>)

### Accessing Weights and Biases of Multilayer Model

These cells demonstrate how to access the weights and biases of the individual layers in the multilayer model.

**Concepts:**

* **Layer-Specific Access:** The code shows how to access the weights and biases of specific layers by their names (e.g., `model1.linear1.weight`).
* **Weights and Biases:** These are the learnable parameters of the neural network that are adjusted during training.

In [33]:
model1.linear1.weight

Parameter containing:
tensor([[-0.2616, -0.3352,  0.3205, -0.0973,  0.3944],
        [-0.4082, -0.2371, -0.0666, -0.0053,  0.3661],
        [ 0.3004, -0.2962, -0.3246, -0.4261, -0.4268]], requires_grad=True)

In [34]:
model1.linear2.weight

Parameter containing:
tensor([[-0.5359, -0.2030,  0.0487]], requires_grad=True)

In [35]:
model1.linear1.bias

Parameter containing:
tensor([0.1821, 0.3284, 0.4057], requires_grad=True)

In [36]:
model1.linear2.bias

Parameter containing:
tensor([0.1410], requires_grad=True)

### Model Summary for Multilayer Model

This cell uses the `summary` function from the `torchinfo` library to display a summary of the architecture of the multilayer model, including layer details, parameters, and input/output shapes.

**Concepts:**

* **Model Summary:** Provides a concise overview of the model's structure.

In [38]:
summary(model1,input_size=(1,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [1, 1]                    --
├─Linear: 1-1                            [1, 3]                    18
├─ReLU: 1-2                              [1, 3]                    --
├─Linear: 1-3                            [1, 1]                    4
├─Sigmoid: 1-4                           [1, 1]                    --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Creating a Multilayer Model using Sequential Container

This cell introduces an alternative way to define a multilayer neural network using PyTorch's `nn.Sequential` container. This approach simplifies the model definition by sequentially stacking layers.

**Concepts:**

* **nn.Sequential:** A container that allows you to define a sequential arrangement of layers.
* **Simplified Model Definition:** `nn.Sequential` makes it easier to create and manage models with multiple layers.


**Containers in PyTorch**

In PyTorch, containers are objects that hold and organize other modules (When there are multiple layers to reduce the complexity we use containers). They provide a way to structure your neural networks and manage their components efficiently. There are several types of containers available in PyTorch:

1. **`nn.Sequential`:** This container is designed to hold a sequence of modules, where the output of one module becomes the input to the next. It is commonly used for building simple feedforward networks.

2. **`nn.ModuleList`:** This container acts like a Python list to store a collection of modules. It allows you to iterate over the modules or access them by index. However, it does not automatically define a forward pass like `nn.Sequential`.

3. **`nn.ModuleDict`:** Similar to `nn.ModuleList`, but it uses a dictionary-like interface to store modules, allowing you to access them by name. It also does not define a forward pass.


**Why use `nn.Sequential`?**

The `nn.Sequential` container is preferred in this case because it offers a concise and straightforward way to define a linear sequence of operations, which is typical for many feedforward neural networks. It automatically handles the connections between layers and defines the forward pass, making the code more readable and easier to manage.

In [42]:
class Model3(nn.Module):
  def __init__(self,no_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(no_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)

    return out

### Instantiating and Using the Sequential Model

This cell creates a fake dataset and an instance of the `Model3` class (the model defined using `nn.Sequential`). It then performs a forward pass.

**Concepts:**

* **Model Instantiation:** Creates an instance of the `Model3` class, passing the number of input features.
* **Forward Pass:** Calls the `forward` method to process the input data.

In [43]:
features = torch.rand(10,5)
model3 = Model3(features.shape[1])
model3(features)

tensor([[0.5894],
        [0.5894],
        [0.5894],
        [0.5894],
        [0.5894],
        [0.5894],
        [0.5894],
        [0.5894],
        [0.5936],
        [0.5894]], grad_fn=<SigmoidBackward0>)